export enum IconType {
  PLUS = "Plus",
  SEND = "Send",
  HEART = "Heart",
  MORE_VERTICAL = "MoreVertical",
  X = "X",
  DASHBOARD = "Dashboard",
  CHAT = "Chat",
  BOT = "Bot",
  NOTE = "Note",
  LOADING = "Loading",
  VIDEO = "Video",
  SETTINGS = "Settings",
  BACK = "ArrowLeft",
  USER = "User",
  SHARE = "Share",
}
